import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FiUser } from "react-icons/fi";
import { MdOutlineExitToApp } from "react-icons/md";

import Navigations from "@/components/Navigations";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {

	return (
		<html lang="en">
			<body className={inter.className} style={{backgroundColor: "#F3F6FD"}} >
				{children}
			</body>
		</html>
	);
}
