import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FiHome, FiFolder, FiUser } from "react-icons/fi";
import { MdOutlineExitToApp } from "react-icons/md";
import { TbCube } from "react-icons/tb";

import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header></header>
				<aside className="flex flex-col justify-between items-start fixed top-0 left-0 bottom-0 min-w-[260px] border-r-[1px] rounded-r-xl  ">
					{/* <Image src="" alt="" /> */}
					<div className="w-full">
						<h1 className="px-6 py-5 text-2xl">Admin</h1>
						<div className="flex items-start flex-col">
							<span className="px-6 pb-3 text-[12px] opacity-[0.67]">
								Главное меню
							</span>
							<ul className="w-full flex flex-col capitalize">
								<li className="opacity-[0.67] pl-6 py-[10px] active-link">
									<Link
										className="flex items-center gap-3"
										href="#"
									>
										<FiHome size="22px" /> Home
									</Link>
								</li>
								<li className="opacity-[0.67] pl-6 py-[10px] ">
									<Link
										className="flex items-center gap-3"
										href="#"
									>
										<TbCube size="22px" /> Goods
									</Link>
								</li>
								<li className="opacity-[0.67] pl-6 py-[10px] ">
									<Link
										className="flex items-center gap-3"
										href="#"
									>
										<FiFolder size="22px" /> Categories
									</Link>
								</li>
							</ul>
						</div>
					</div>
					<div>
						<Link className="block opacity-[0.67] ml-6 py-[10px]" href="#">
							<button className="flex items-center gap-3">
								<FiUser size="22px" /> Account
							</button>
						</Link>
						<Link className="block opacity-[0.67] ml-6 py-[10px]" href="#">
							<button className="flex items-center gap-3">
								<MdOutlineExitToApp size="22px" /> Exit
							</button>
						</Link>
					</div>
				</aside>
				{children}
				<footer></footer>
			</body>
		</html>
	);
}
